### PR TITLE
Added uninstall option, new panel and more

### PR DESCRIPTION
**Pull request by navelpluisje**
Added panel to manage already installed packages
Within the panel now possible to delete packages
If there already is a config file, the installed panel will be shown
Added buttons in the titlebar of the panel with the next buttons:
- show configuration panel
- show already installed packages
- show the install quick panel
Added icon font for buttons

### CODE REVIEW

**Comment by navelpluisje** [comment]
Forgot to mention that the save option is added for both install and uninstall

**Comment by albertinad** [comment]
Hi, I will be reviewing your PR. Some of the features that you implemented are under development right now, following a design for the feature. Thanks!

**Comment by navelpluisje** [comment]
@albertinad, just looking through the code and i made a mixed up about .bowerrc and bower.json.
My changes only work with an already installed bower.json file.

**Comment by navelpluisje** [comment]
@albertinad , Made some adjustments for the installed packages. Als able now to generate a default bower.json

**Comment by albertinad** [comment]
I will take a look at it today, but first please updage your repository from the upstream, since most of your changes are already implemented and a lot of new changes, related to the design, (base components, ConfigurationManager, DependenciesManage, BowerFile etc).

**Comment by navelpluisje** [comment]
@albertinad, maybe a stupid question, but how do i update my fork with your latest updates?

**Comment by albertinad** [comment]
Not a stupid question :) 
To keep your fork in sync with the mainstream you need to add it as another remote,
`git remote add upstream https://github.com/njx/brackets-bower.git`
and then, to pull the remote changes,
`git fetch upstream`
Make sure that you are on your master branch,
`git merge upstream/master`

Here is the documentation related to forks:
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

**Comment by navelpluisje** [comment]
@albertinad  Merged the whole bunch now with your latest version. Not ready to merge for you directly.
I saw there is a lot going on indeed. From the things we did both, I will remove mine and where necessary extending yours.

Because most parts are already there I will focus on the panel for listing end removing installed packages.

**Comment by albertinad** [comment]
That's great! Please file an issue and make a branch on your fork so I know that you're working on that :)
If you have any question, doubt or want to discuss some design things, lets use that issue.
Thanks!

**Comment by albertinad** [comment]
@navelpluisje I forgot, I like the icon/styles that you added, can you create a branch on your fork that only contains those little changes (icons) ? I can merge it as soon as you finish. There's an issue for that: #28

**Pull request closed without merging**
